// mobile/components/forum/TopicCardSkeleton.tsx
import { View } from 'react-native';
import { colors } from '@/lib/theme/colors';
import { useColorScheme } from '@/components/useColorScheme';
import { SkeletonBlock } from './SkeletonBlock';

export function TopicCardSkeleton() {
	const colorScheme = useColorScheme();
	const theme = colorScheme === 'dark' ? colors.dark : colors.light;

	return (
		<View
			style={{
				backgroundColor: theme.bgPrimary,
				borderRadius: 12,
				padding: 14,
				borderWidth: 1,
				borderColor: theme.border,
			}}>
			{/* Title */}
			<SkeletonBlock width="75%" height={18} borderRadius={4} />
			{/* Body lines */}
			<View style={{ marginTop: 8, gap: 6 }}>
				<SkeletonBlock width="100%" height={14} borderRadius={4} />
				<SkeletonBlock width="60%" height={14} borderRadius={4} />
			</View>
			{/* Author row */}
			<View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 }}>
				<SkeletonBlock width={28} height={28} borderRadius={14} />
				<SkeletonBlock width={80} height={12} borderRadius={4} />
			</View>
			{/* Stats row */}
			<View
				style={{
					flexDirection: 'row',
					gap: 14,
					marginTop: 10,
					paddingTop: 10,
					borderTopWidth: 1,
					borderTopColor: theme.border,
				}}>
				<SkeletonBlock width={40} height={12} borderRadius={4} />
				<SkeletonBlock width={40} height={12} borderRadius={4} />
				<SkeletonBlock width={40} height={12} borderRadius={4} />
			</View>
		</View>
	);
}

// src/lib/components/forum/TopicCardSkeleton.svelte
<script lang="ts">
  import Skeleton from '$lib/components/ui/Skeleton.svelte';
</script>

<div class="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800/90 shadow-card">
  <div class="p-4 sm:p-5">
    <!-- Author row -->
    <div class="flex items-center gap-2.5 mb-3">
      <Skeleton class="!rounded-full flex-shrink-0" width="28px" height="28px" />
      <Skeleton width="100px" height="0.75rem" />
    </div>

    <!-- Title -->
    <Skeleton width="75%" height="1.25rem" class="mb-2" />

    <!-- Body preview -->
    <Skeleton width="100%" height="0.75rem" class="mb-1.5" />
    <Skeleton width="60%" height="0.75rem" />

    <!-- Stats row -->
    <div class="mt-3 flex items-center gap-4">
      <Skeleton width="40px" height="0.75rem" />
      <Skeleton width="40px" height="0.75rem" />
      <Skeleton width="40px" height="0.75rem" />
    </div>
  </div>
</div>
