// src/lib/components/weather/WeatherSummaryCard.svelte
<script lang="ts">
  import type { ForecastResponse, DayForecast } from '$lib/types/database';
  import { weatherCodeToDescription, degreesToCardinal } from '$lib/utils/weather';
  import WeatherIcon from './WeatherIcon.svelte';
  import HikerInsights from './HikerInsights.svelte';

  interface Props {
    forecast: ForecastResponse;
  }

  let { forecast }: Props = $props();

  const summit = $derived(forecast.bands.summit);
  const today = $derived(summit.days[0]);
  const upcoming = $derived(summit.days.slice(1, 4));

  // Use afternoon as "current" conditions, fall back to morning
  const current = $derived(today?.afternoon ?? today?.morning);

  // Top insight by severity
  const topInsight = $derived(forecast.insights[0] ?? null);

  function timeAgo(dateStr: string): string {
    const date = new Date(dateStr);
    const now = new Date();
    const hours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
    if (hours < 1) return 'Just now';
    if (hours === 1) return '1 hour ago';
    if (hours < 24) return `${hours} hours ago`;
    const days = Math.floor(hours / 24);
    if (days === 1) return '1 day ago';
    return `${days} days ago`;
  }

  function formatShortDay(dateStr: string): string {
    const date = new Date(dateStr + 'T12:00:00');
    return date.toLocaleDateString('en-US', { weekday: 'short' });
  }

  // Most representative weather code for the day (afternoon, then morning)
  function dayIcon(day: DayForecast): number {
    return day.afternoon.weather_code;
  }
</script>

{#if today && current}
  <section class="mt-10 animate-fade-in-up" style="animation-delay: 175ms">
    <h2 class="heading-section text-slate-900 dark:text-white flex items-center gap-2 mb-4">
      <svg class="h-6 w-6 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
      </svg>
      Summit Weather
    </h2>

    <div class="rounded-xl border border-slate-200 dark:border-slate-700 bg-gradient-to-br from-slate-50 to-white dark:from-slate-800 dark:to-slate-800/50 shadow-card overflow-hidden">
      <!-- Current conditions -->
      <div class="p-6">
        <div class="flex flex-wrap items-start justify-between gap-6">
          <div class="flex items-center gap-4">
            <div class="h-16 w-16 rounded-2xl bg-accent/10 flex items-center justify-center">
              <WeatherIcon code={current.weather_code} class="h-10 w-10" />
            </div>
            <div>
              <div class="flex items-baseline gap-2">
                <span class="text-4xl font-bold text-slate-900 dark:text-white">{current.temperature_f}°</span>
                {#if current.feels_like_f !== current.temperature_f}
                  <span class="text-sm text-slate-500 dark:text-slate-400">Feels {current.feels_like_f}°</span>
                {/if}
              </div>
              <p class="text-slate-600 dark:text-slate-400">{weatherCodeToDescription(current.weather_code)}</p>
            </div>
          </div>

          <div class="flex flex-wrap gap-6">
            <div class="text-center">
              <span class="block text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400">High / Low</span>
              <span class="text-lg font-semibold text-slate-900 dark:text-white">{today.high_f}° / {today.low_f}°</span>
            </div>
            <div class="text-center">
              <span class="block text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400">Wind</span>
              <span class="text-lg font-semibold text-slate-900 dark:text-white">
                {current.wind_speed_mph} mph {degreesToCardinal(current.wind_direction)}
              </span>
            </div>
            {#if current.snow_in > 0}
              <div class="text-center">
                <span class="block text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400">Snow</span>
                <span class="text-lg font-semibold text-sky-500">{current.snow_in}"</span>
              </div>
            {:else if current.precipitation_in > 0}
              <div class="text-center">
                <span class="block text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400">Precip</span>
                <span class="text-lg font-semibold text-blue-500">{current.precipitation_in}"</span>
              </div>
            {/if}
          </div>
        </div>

        {#if forecast.fetched_at}
          <p class="mt-4 text-xs text-slate-400 dark:text-slate-500">
            Updated {timeAgo(forecast.fetched_at)}
          </p>
        {/if}
      </div>

      <!-- 3-day mini forecast -->
      {#if upcoming.length > 0}
        <div class="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-900/30 p-4">
          <div class="grid grid-cols-3 gap-3">
            {#each upcoming as day}
              <div class="text-center p-2 rounded-lg hover:bg-white dark:hover:bg-slate-800 transition-colors">
                <span class="block text-xs font-medium text-slate-500 dark:text-slate-400">{formatShortDay(day.date)}</span>
                <div class="my-1 flex justify-center">
                  <WeatherIcon code={dayIcon(day)} class="h-6 w-6" />
                </div>
                <span class="text-sm font-semibold text-slate-900 dark:text-white">{day.high_f}°</span>
                <span class="text-sm text-slate-400 dark:text-slate-500"> / {day.low_f}°</span>
              </div>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Top insight -->
      {#if topInsight}
        <div class="border-t border-slate-200 dark:border-slate-700 px-4 py-3">
          <HikerInsights insights={[topInsight]} />
        </div>
      {/if}

      <!-- View Full Forecast link -->
      <div class="border-t border-slate-200 dark:border-slate-700 px-4 py-3 bg-slate-50/50 dark:bg-slate-900/20">
        <a
          href="/peaks/{forecast.peak.slug}/weather"
          class="flex items-center justify-center gap-2 w-full py-2 rounded-lg text-sm font-medium text-accent hover:bg-accent/10 transition-colors"
        >
          View Full Forecast
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
          </svg>
        </a>
      </div>
    </div>
  </section>
{/if}

// mobile/components/weather/WeatherSummaryCard.tsx
import { View, Text, Pressable } from 'react-native';
import { SymbolView } from 'expo-symbols';
import { colors } from '@/lib/theme/colors';
import { WeatherIcon } from './WeatherIcon';
import {
  weatherCodeToDescription,
  degreesToCardinal,
  getTemperatureColor,
} from '@saltgoat/shared/utils/weather';
import type { ForecastResponse, HikerInsight } from '@/lib/types/api';

const TEMP_COLORS: Record<string, string> = {
  violet: '#7C3AED',
  blue: '#2B6CB0',
  sky: '#3182CE',
  neutral: colors.light.textPrimary,
  amber: '#D69E2E',
  orange: '#DD6B20',
  red: '#E53E3E',
};

const SEVERITY_COLORS: Record<HikerInsight['severity'], string> = {
  info: '#2B6CB0',
  caution: '#975A16',
  warning: '#C05621',
  danger: '#C53030',
};

interface WeatherSummaryCardProps {
  forecast: ForecastResponse;
  onViewFull: () => void;
}

export function WeatherSummaryCard({ forecast, onViewFull }: WeatherSummaryCardProps) {
  const summit = forecast.bands.summit;
  const today = summit.days[0];
  if (!today) return null;

  // Use current period based on time of day
  const hour = new Date().getHours();
  const currentPeriod = hour < 12 ? today.morning : hour < 18 ? today.afternoon : today.night;
  const tempColor = TEMP_COLORS[getTemperatureColor(currentPeriod.temperature_f)] || colors.light.textPrimary;
  const description = weatherCodeToDescription(currentPeriod.weather_code);
  const windDir = degreesToCardinal(currentPeriod.wind_direction);

  // Top-severity insight
  const topInsight = forecast.insights[0];

  return (
    <View style={{ gap: 12 }}>
      {/* Current conditions */}
      <View
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: colors.light.bgSecondary,
          borderRadius: 12,
          padding: 14,
          gap: 12,
          borderWidth: 1,
          borderColor: colors.light.border,
        }}
      >
        <WeatherIcon code={currentPeriod.weather_code} size={32} tintColor={tempColor} />

        <View style={{ flex: 1 }}>
          <View style={{ flexDirection: 'row', alignItems: 'baseline', gap: 6 }}>
            <Text style={{ fontFamily: 'Inter-Bold', fontSize: 24, color: tempColor }}>
              {Math.round(currentPeriod.temperature_f)}{String.fromCharCode(176)}
            </Text>
            <Text style={{ fontFamily: 'Inter', fontSize: 13, color: colors.light.textMuted }}>
              feels {Math.round(currentPeriod.feels_like_f)}{String.fromCharCode(176)}
            </Text>
          </View>
          <Text style={{ fontFamily: 'Inter-Medium', fontSize: 13, color: colors.light.textSecondary }}>
            {description}
          </Text>
        </View>

        <View style={{ alignItems: 'flex-end' }}>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: colors.light.textMuted }}>
            {currentPeriod.wind_speed_mph} mph {windDir}
          </Text>
          <Text style={{ fontFamily: 'Inter', fontSize: 12, color: colors.light.textMuted }}>
            H: {Math.round(today.high_f)}{String.fromCharCode(176)} L: {Math.round(today.low_f)}{String.fromCharCode(176)}
          </Text>
        </View>
      </View>

      {/* 3-day mini forecast */}
      <View style={{ flexDirection: 'row', gap: 8 }}>
        {summit.days.slice(0, 3).map((day, i) => {
          const date = new Date(day.date + 'T12:00:00');
          const label = i === 0 ? 'Today' : date.toLocaleDateString('en-US', { weekday: 'short' });
          const amCode = day.morning.weather_code;
          const pmCode = day.afternoon.weather_code;

          return (
            <View
              key={day.date}
              style={{
                flex: 1,
                backgroundColor: colors.light.bgSecondary,
                borderRadius: 10,
                padding: 10,
                alignItems: 'center',
                borderWidth: 1,
                borderColor: colors.light.border,
              }}
            >
              <Text style={{ fontFamily: 'Inter-Medium', fontSize: 12, color: colors.light.textSecondary }}>
                {label}
              </Text>
              <View style={{ flexDirection: 'row', gap: 4, marginVertical: 6 }}>
                <WeatherIcon code={amCode} size={16} />
                <WeatherIcon code={pmCode} size={16} />
              </View>
              <Text style={{ fontFamily: 'Inter-SemiBold', fontSize: 13, color: colors.light.textPrimary }}>
                {Math.round(day.high_f)}{String.fromCharCode(176)} / {Math.round(day.low_f)}{String.fromCharCode(176)}
              </Text>
            </View>
          );
        })}
      </View>

      {/* Top insight */}
      {topInsight && (
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            paddingHorizontal: 4,
          }}
        >
          <SymbolView
            name="exclamationmark.triangle.fill"
            size={14}
            tintColor={SEVERITY_COLORS[topInsight.severity]}
            style={{ width: 14, height: 14 }}
          />
          <Text
            style={{
              fontFamily: 'Inter-Medium',
              fontSize: 13,
              color: SEVERITY_COLORS[topInsight.severity],
              flex: 1,
            }}
            numberOfLines={1}
          >
            {topInsight.title}
          </Text>
        </View>
      )}

      {/* Full forecast link */}
      <Pressable
        onPress={onViewFull}
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          paddingVertical: 10,
          borderRadius: 10,
          backgroundColor: colors.mountain.blue + '0A',
          borderWidth: 1,
          borderColor: colors.mountain.blue + '20',
          gap: 6,
        }}
      >
        <Text
          style={{
            fontFamily: 'Inter-SemiBold',
            fontSize: 14,
            color: colors.mountain.blueLight,
          }}
        >
          Full Forecast
        </Text>
        <SymbolView
          name="chevron.right"
          size={12}
          tintColor={colors.mountain.blueLight}
          style={{ width: 12, height: 12 }}
        />
      </Pressable>
    </View>
  );
}
